### ISSUE TITLE
RapidFuzz update breaks wajig

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/wajig#1]
Now seeing the following on any call to wajig: (e.g., wajig reboot)

Traceback (most recent call last):
  File "/home/gjw/.local/bin/wajig", line 8, in <module>
    sys.exit(main())
  File "/home/gjw/.local/lib/python3.8/site-packages/wajig/__init__.py", line 1174, in main
    matched_cmd = util.get_misspelled_command(cmd, choices)
  File "/home/gjw/.local/lib/python3.8/site-packages/wajig/util.py", line 123, in get_misspelled_command
    matched, score = find_best_match(command, available_commands)
ValueError: too many values to unpack (expected 2)

**Comment by gjwgit** [comment]
Fixed.
