### ISSUE TITLE
wajig has an unmarked dependency on python-apt

### ISSUE THREAD

**Issue by martindemello** [gjwgit/wajig#3]
`wajig` installs from pip without any issues, but when I run it it crashes due to the `apt` module not being found. however, that seems to be an ancient and unmaintained package which no longer even installs:

```
$ pip install python-apt
Collecting python-apt
  Using cached python-apt-0.7.8.tar.bz2 (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b_2l_d2u/python-apt_b6e8252e1fae45699fcbe36ce61bb81f/setup.py", line 6, in <module>
          from DistUtilsExtra.command import *
      ModuleNotFoundError: No module named 'DistUtilsExtra'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by gjwgit** [comment]
With reference to the comment that wajig won't work from a pip install can you provide details.

I've tested on a clean Debian 12 on Linode

```
# apt update
# apt upgrade 
# apt install python3-pip

$ pip install wajig --break-system-packages
$ wajig --version
wajig 4.0.12
```

Seems to work just fine

**Comment by martindemello** [comment]
maybe it's just that my debian is old then

```
$ wajig
Traceback (most recent call last):
  File "/home/martin/.venv/bin/wajig", line 11, in <module>
    load_entry_point('wajig==4.0.12', 'console_scripts', 'wajig')()
  File "/home/martin/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/martin/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/martin/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/martin/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/martin/.venv/lib/python3.9/site-packages/wajig/__init__.py", line 26, in <module>
    import wajig.util as util
  File "/home/martin/.venv/lib/python3.9/site-packages/wajig/util.py", line 13, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'

$ uname -a
Linux martindemello 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

$ pip install wajig --break-system-packages

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --break-system-packages
```

**Comment by gjwgit** [comment]
The `--break-system-packages` is for newer Debian (probably 12). You can drop that command line option for older Debian.

Tested on a fresh Debian 11 on Linode as below. Seems to work out of the box. You might be better off installing the system python3-apt package `apt install python3-apt` then try pip install of wajig again. Let me know how you go.

```
# uname -a
Linux localhost 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
# apt update
# apt upgrade 
# apt install python3-pip
```

```
$ pip install wajig
$ wajig version
wajig 4.0.12 rapidfuzz.fuzz
$ wajig
wajig>
$

**Comment by martindemello** [comment]
confirmed; system `python3-apt` does satisfy the requirement, and everything works after that.
