### ISSUE TITLE
`purgeorphans` does not work

### ISSUE THREAD

**Issue by rrthomas** [gjwgit/wajig#8]
Installing wajig from git with `make install` on my Ubuntu 22.04 system, I get:

```
$ wajig purgeorphans
Traceback (most recent call last):
  File "/home/rrt/.local/share/wajig/__init__.py", line 1215, in <module>
    main()
  File "/home/rrt/.local/share/wajig/__init__.py", line 1211, in main
    result.func(result)
  File "/home/rrt/.local/share/wajig/wajig/commands.py", line 824, in purgeorphans
    perform.execute(command, root=True, log=True, teach=args.teach, noop=args.noop)
AttributeError: 'Namespace' object has no attribute 'teach'
```

`purgeremoved` gives a similar error.

I have a PR to fix them.

**Comment by rrthomas** [comment]
See PR #9. I didn't systematically go through the code to see if there were other missing `parents`.

**Comment by gjwgit** [comment]
Reproduced. PR confirmed. `make install`. Issue fixed. Thanks.
